[serviceweaver]
binary = ".\\harmony-engine.exe"

[single]
listeners.bin = {address = "localhost:9000"}

[multi]
listeners.bin = {address = "localhost:9000"}

["harmony-engine/Prompter"]
Driver = "mysql"
Source = "root:@tcp(localhost:3306)/harmony"
